In [1]:
from datetime import datetime
import pandas as pd
import geopandas as gpd

In [2]:
# Predefined variable for title and version
date = datetime.now()
# Enter
initials = "mw"
site = "samoa"

version = f"{initials}-{site}-{date.strftime('%d%m%Y')}"
print(version)

mw-samoa-27022026

In [3]:
# Read reference tdata with correct schema 
tdata = gpd.read_file(f"training-data/{version}.geojson")

In [4]:
tdata

      lulc_class  value_id                      geometry
0    Settlements         5  POINT (-171.80608 -13.82372)
1    Settlements         5   POINT (-171.8146 -13.82825)
2    Settlements         5  POINT (-171.81379 -13.82703)
3    Settlements         5   POINT (-171.8214 -13.82675)
4    Settlements         5   POINT (-171.80683 -13.8275)
..           ...       ...                           ...
393    Grassland         3  POINT (-172.10402 -13.84666)
394    Grassland         3  POINT (-172.10385 -13.84695)
395    Grassland         3  POINT (-172.10818 -13.84091)
396    Grassland         3   POINT (-172.10788 -13.8411)
397    Grassland         3   POINT (-172.1087 -13.84097)

[398 rows x 3 columns]

In [5]:
tdata = gpd.read_file("training-data/mw-samoa-27022026.geojson")

In [6]:
print('list of', tdata['lulc_class'].nunique(),'unique classes')
print(tdata['lulc_class'].unique())

list of 6 unique classes
['Settlements' 'Forest' 'Cropland' 'Grassland' 'Wetlands' 'Land']

In [7]:
print(tdata['lulc_class'].value_counts())
print('total gps points',(len(tdata)))

lulc_class
Settlements    92
Land           79
Forest         72
Grassland      55
Cropland       50
Wetlands       50
Name: count, dtype: int64
total gps points 398

In [8]:
# tdata.loc[tdata['LULC_class'] == 'Shrubs', 'LULC_class'] = 'Grassland'

# tdata.loc[tdata['LULC_class'] == 'Shallow_ocean', 'LULC_class'] = 'Water'
# tdata.loc[tdata['LULC_class'] == 'Coral_reef', 'LULC_class'] = 'Water'
# tdata.loc[tdata['LULC_class'] == 'Seagrass', 'LULC_class'] = 'Water'
# tdata.loc[tdata['LULC_class'] == 'Deep_ocean', 'LULC_class'] = 'Water'
# tdata.loc[tdata['LULC_class'] == 'Surface_water', 'LULC_class'] = 'Water'

In [9]:
# tdata.loc[tdata['LULC_class'] == 'Grassland', 'LULC_class'] = 'Grazing_Cropland'
# tdata.loc[tdata['LULC_class'] == 'Cropland', 'LULC_class'] = 'Grazing_Cropland'

In [10]:
# Define two lists
old_categories = ['Forest', 'Cropland', 'Grassland', 'Wetlands', 'Settlements', 'Land']
new_groups = [1, 2, 3, 4, 5, 6]

# Create the mapping dictionary
category_mapping = dict(zip(old_categories, new_groups))

# Apply mapping
tdata['lulc_code'] = tdata['lulc_class'].map(category_mapping)

In [11]:
print(tdata['lulc_code'].value_counts())
print('total gps points',(len(tdata)))

lulc_code
5    92
6    79
1    72
3    55
2    50
4    50
Name: count, dtype: int64
total gps points 398

In [12]:
len(tdata)

398

In [13]:
# 1) Show current cross-tab of class -> codes to inspect inconsistency
print("Cross-tab of LULC_class vs LULC_code (counts):")
ct = pd.crosstab(tdata['lulc_class'], tdata['lulc_code'])
display(ct)

Cross-tab of LULC_class vs LULC_code (counts):

lulc_code     1   2   3   4   5   6
lulc_class
Cropland      0  50   0   0   0   0
Forest       72   0   0   0   0   0
Grassland     0   0  55   0   0   0
Land          0   0   0   0   0  79
Settlements   0   0   0   0  92   0
Wetlands      0   0   0  50   0   0

In [14]:
tdata.explore(column='lulc_class')

In [15]:
# tdata = tdata.drop(columns=["fid"])
# tdata = tdata.drop(columns=["id"])
# tdata = tdata.drop(columns=["Descriptio"])
# tdata = tdata.drop(columns=["Long"])
# tdata = tdata.drop(columns=["Lat"])
# tdata

In [16]:
print(tdata['lulc_code'].value_counts())
print('total gps points',(len(tdata)))

lulc_code
5    92
6    79
1    72
3    55
2    50
4    50
Name: count, dtype: int64
total gps points 398

In [17]:
tdata.to_file("training-data/"f"{version}_postcard_4.geojson")